apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-backend
spec:
  replicas: 1
  selector:
    matchLabels: { app: survey-backend }
  template:
    metadata:
      labels: { app: survey-backend }
    spec:
      containers:
        - name: api
          image: jaimeteto/survey-backend:hw3
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: survey-backend-svc
spec:
  selector: { app: survey-backend }
  ports:
    - port: 8000
      targetPort: 8000
