apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-frontend
spec:
  replicas: 1
  selector:
    matchLabels: { app: survey-frontend }
  template:
    metadata:
      labels: { app: survey-frontend }
    spec:
      containers:
        - name: web
          image: jaimeteto/survey-frontend:hw3
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_BASE_URL
              value: "http://survey-backend-svc:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: survey-frontend-svc
spec:
  selector: { app: survey-frontend }
  ports:
    - port: 80
      targetPort: 80
